-- Enforce idempotency for web payment receipts at the DB level to close the
-- TOCTOU race in PayPal capture-order and PortOne checkout flows.
--
-- =====================================================================
--   MANUAL APPLICATION REQUIRED — DO NOT APPLY VIA `supabase db push`
-- =====================================================================
--
-- This migration MUST be applied via the Supabase Dashboard SQL Editor
-- (or `psql` invoked WITHOUT a transaction, e.g. `psql -1` is forbidden;
-- use plain `psql -f` with autocommit). It MUST NOT be applied via
-- `supabase db push` or `supabase migration up`.
--
-- Why: the Supabase CLI wraps each migration file in an implicit
-- BEGIN/COMMIT before executing it (see supabase/cli#2898). PostgreSQL
-- forbids `CREATE INDEX CONCURRENTLY` inside a transaction block and will
-- abort the migration with:
--     ERROR: 25001  CREATE INDEX CONCURRENTLY cannot run inside a
--                   transaction block
--
-- Deployment runbook (perform in this exact order):
--
--   1. Apply the cleanup migration via the CLI normally:
--        supabase db push  -- picks up 20260424000000_cleanup_duplicate_web_receipts.sql
--      (That file is plain DML and is safe inside the CLI's transaction wrapper.)
--
--   2. Open the Supabase Dashboard → SQL Editor for project
--      `xtijtefcycoeqludlngc`.
--
--   3. Copy the DDL block at the bottom of THIS file (the CREATE INDEX
--      CONCURRENTLY statement and the COMMENT ON INDEX statement) and run
--      them one at a time in the SQL Editor. The SQL Editor runs each
--      submission outside an explicit transaction, so CONCURRENTLY works.
--
--   4. Verify the index exists and is VALID:
--        SELECT indexname, indexdef
--          FROM pg_indexes
--         WHERE schemaname = 'public'
--           AND tablename  = 'receipts'
--           AND indexname  = 'receipts_web_completed_unique';
--
--        SELECT i.relname, ix.indisvalid, ix.indisready
--          FROM pg_class i
--          JOIN pg_index ix ON ix.indexrelid = i.oid
--         WHERE i.relname = 'receipts_web_completed_unique';
--      Expect: indisvalid = true, indisready = true.
--
--   5. Mark this migration as applied so the CLI does not try to re-run it
--      on the next `supabase db push`:
--        INSERT INTO supabase_migrations.schema_migrations (version, name, statements)
--        VALUES (
--          '20260424000001',
--          'add_receipts_web_unique_index',
--          ARRAY[
--            'CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS receipts_web_completed_unique ON public.receipts (receipt_hash) WHERE platform = ''web'' AND status = ''completed'' AND receipt_hash IS NOT NULL;'
--          ]
--        );
--
-- Failure recovery:
--   If CONCURRENTLY mid-build fails (e.g. a duplicate slipped in between
--   the cleanup migration and this run), Postgres leaves an INVALID index
--   that will silently be ignored by the planner but blocks a retry of
--   the same name. Drop it before retrying:
--
--     DROP INDEX CONCURRENTLY public.receipts_web_completed_unique;
--
--   Then re-identify any new duplicates with the diagnostic in
--   20260424000000_cleanup_duplicate_web_receipts.sql, clean them up,
--   and re-run step 3.
--
-- Why we accept this awkward two-step process:
--   The `receipts` table is hot-path payment infrastructure. A non-
--   CONCURRENTLY CREATE INDEX takes a ShareLock and blocks all
--   INSERT/UPDATE/DELETE on `receipts` for the duration of the build,
--   which on a sizeable receipts table is tens of seconds of stalled
--   live payments. The manual SQL Editor step is a one-time cost; the
--   zero-downtime build is permanent.
--
-- ============== CODE DEPLOYMENT ORDERING ==============
-- The migration files in this PR have a strict apply order. Code deploy must
-- happen LAST. Out-of-order application leaves money on the table:
--
--   1. CLI:          20260424000000_cleanup_duplicate_web_receipts.sql
--                    (`supabase db push` — plain DML, safe in CLI's tx wrapper)
--   2. SQL Editor:   The DDL block at the bottom of THIS file
--                    (CREATE INDEX CONCURRENTLY + COMMENT, manual step)
--                    + INSERT into supabase_migrations.schema_migrations
--                      (see step 5 above) so CLI doesn't try to re-run it
--   3. CLI:          20260424000002_create_process_paypal_capture_rpc.sql
--                    (PayPal RPC + GRANT EXECUTE TO service_role only)
--   4. CLI:          20260424000003_create_process_portone_capture_rpc.sql
--                    (PortOne RPC + GRANT EXECUTE TO service_role only)
--   5. App deploy:   route.ts changes
--                    - app/api/payment/paypal/capture-order/route.ts
--                      (invokes process_paypal_capture via service-role client)
--                    - app/api/payment/portone/webhook/route.ts
--                      (invokes process_portone_capture via service-role client)
--
-- Why steps 3 and 4 are independent CLI files (not unified):
--   The two RPCs share an identical structure but stay separate so the
--   PURCHASE_<paymentId> vs PAYPAL_<orderId> transaction_id prefixes (and
--   provider-specific receipt payload shapes) remain stable for analytics /
--   CS / refund tooling. See the file header of
--   20260424000003_create_process_portone_capture_rpc.sql for the full
--   rationale.
--
-- Ordering hazards:
--   - Code deployed BEFORE step 3 OR step 4 (one of the RPCs missing): the
--     corresponding payment path returns 500 "Failed to record payment" and
--     the user is uncredited. Receipt insert never happens because the route
--     now goes through the RPC; rollback of the code deploy is the recovery.
--     IMPORTANT: PayPal and PortOne are independent — if only one RPC is
--     deployed, only the matching provider's route can be safely rolled out.
--     Do not deploy a PR that updates both routes until both RPCs exist.
--   - RPC applied BEFORE code deploy: SAFE. The route still calls the old
--     direct-insert path until the new bundle is live.
--   - Code + RPC applied BEFORE the unique index is in place: SAFE-ISH. The
--     RPC's pre-check on history rows still catches most duplicate captures,
--     but the partial-index TOCTOU race window reopens. Don't sit in this
--     state long. Especially risky for PortOne, where webhook retries can
--     fire concurrent inserts within milliseconds.
--   - Index applied BEFORE the cleanup migration: CREATE INDEX CONCURRENTLY
--     will fail or build INVALID against existing duplicates. Always run
--     step 1 first.
--   - PortOne webhook re-enabled BEFORE step 4: PortOne will keep retrying
--     for up to ~24h. Every retry will 500 until process_portone_capture
--     exists, but no double-credit can occur — the webhook now wraps every
--     write in the RPC's transaction. Backlog clears automatically once the
--     RPC is in place.
--
-- ============== ROLLBACK ==============
-- Reverse the steps above:
--
--   1. Roll back the app deploy first (so neither route calls its RPC).
--      Both routes (PayPal capture-order + PortOne webhook) must roll back
--      in the same deploy — leaving one calling its RPC while the other
--      reverts to direct-insert is supported but pointless.
--   2. Drop the PortOne RPC:
--        DROP FUNCTION IF EXISTS public.process_portone_capture(
--          uuid, text, text, int, int, numeric, text, text, text, text,
--          jsonb, jsonb, timestamptz
--        );
--      DELETE the matching schema_migrations row for 20260424000003.
--   3. Drop the PayPal RPC:
--        DROP FUNCTION IF EXISTS public.process_paypal_capture(
--          uuid, text, text, text, int, int, text, text, text, text,
--          jsonb, jsonb, timestamptz
--        );
--      DELETE the matching schema_migrations row for 20260424000002.
--   4. Drop the partial unique index (Dashboard SQL Editor — CONCURRENTLY
--      again because the table is hot):
--        DROP INDEX CONCURRENTLY IF EXISTS public.receipts_web_completed_unique;
--      DELETE the matching schema_migrations row for 20260424000001.
--   5. Cleanup migration (000000) is data-only normalization and does not
--      need to be reverted unless the new state caused a regression. If it
--      did, restore from the dated backup snapshot taken before this PR.
--
-- Scope choice: platform = 'web' AND status = 'completed' only.
--   - iOS/Android receipts legitimately repeat the same receipt_hash across
--     rows (App Store / Play Store re-validation is surfaced with
--     status = 'duplicate'). A cross-platform unique index would clash with
--     thousands of these intentional rows.
--   - Web payments (PayPal orderID, PortOne PAY_xxx) are expected to be unique
--     per capture. A duplicate completed row there indicates a real race or
--     double-credit.
--
-- Pre-existing duplicates were normalized by the companion migration
-- 20260424000000_cleanup_duplicate_web_receipts.sql.
--
-- ============== ACTUAL DDL BELOW (copy into SQL Editor) ==============

CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS receipts_web_completed_unique
  ON public.receipts (receipt_hash)
  WHERE platform = 'web'
    AND status = 'completed'
    AND receipt_hash IS NOT NULL;

COMMENT ON INDEX public.receipts_web_completed_unique IS
  'Enforces idempotency for web payment receipts keyed by receipt_hash. '
  'Scoped to platform=web + status=completed to avoid clashing with iOS/Android '
  'duplicate markers. Application code (PayPal capture-order route, PortOne '
  'webhook) catches the resulting 23505 unique_violation as the canonical '
  '"already processed" signal.';
